version: '3'

services:
  # Configuración del servicio de MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  # Configuración del servicio de tu aplicación Spring Boot
  springboot-application:
    build: .
    container_name: springboot-application
    ports:
      - "8082:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://host.docker.internal:27017/Tarea2
